# Generated by Django 5.1.2 on 2024-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_receipe_view_count_receipe_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_view_count',
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='user',
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to='receipe'),
        ),
    ]
